In [33]:
import torch
import torch.nn as nn
import torch.nn.utils.prune as prune

In [34]:
link = nn.Conv2d(12, 48, 1)

In [35]:
prune.ln_structured(link, name='weight', amount=36, n=2, dim=0)

Conv2d(12, 48, kernel_size=(1, 1), stride=(1, 1))

In [28]:
class FooBarPruningMethod(prune.BasePruningMethod):
    """Prune every other entry in a tensor
    """
    PRUNING_TYPE = 'unstructured'

    def compute_mask(self, t, default_mask):
        print(default_mask)
        mask = default_mask.clone()
        mask.view(-1)[::2] = 0
        print(mask)
        return mask

In [29]:
def foobar_unstructured(module, name):

    FooBarPruningMethod.apply(module, name)
    return module


In [30]:
foobar_unstructured(link, 'weight')

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 

Conv2d(12, 48, kernel_size=(1, 1), stride=(1, 1))

In [40]:
for i in list(link.named_parameters()):
    print(i[0])

bias
weight_orig


In [47]:
link
for i in list(link.named_parameters()):
    print(i[0])

bias
weight_orig


In [54]:
torch.nn.init.kaiming_uniform_(link.weight_orig)

Parameter containing:
tensor([[[[-0.5468]],

         [[ 0.4270]],

         [[-0.1875]],

         [[ 0.3571]],

         [[-0.1104]],

         [[ 0.2171]],

         [[-0.7008]],

         [[ 0.0302]],

         [[-0.5611]],

         [[ 0.3771]],

         [[ 0.5127]],

         [[ 0.6448]]],


        [[[ 0.3839]],

         [[-0.5470]],

         [[ 0.0221]],

         [[ 0.4965]],

         [[ 0.6492]],

         [[-0.4090]],

         [[ 0.0533]],

         [[-0.5564]],

         [[-0.0849]],

         [[-0.4233]],

         [[-0.3370]],

         [[ 0.6417]]],


        [[[ 0.0076]],

         [[-0.3507]],

         [[-0.6717]],

         [[ 0.2492]],

         [[ 0.0684]],

         [[-0.2481]],

         [[-0.3567]],

         [[ 0.1873]],

         [[-0.0224]],

         [[ 0.1787]],

         [[ 0.2749]],

         [[ 0.1165]]],


        [[[ 0.1707]],

         [[-0.2243]],

         [[ 0.1290]],

         [[-0.2983]],

         [[ 0.1293]],

         [[-0.3915]],

      

In [55]:
link.weight

tensor([[[[-0.1593]],

         [[ 0.0043]],

         [[-0.1957]],

         [[-0.1114]],

         [[ 0.1162]],

         [[ 0.2408]],

         [[-0.0460]],

         [[-0.2849]],

         [[ 0.2410]],

         [[-0.0162]],

         [[-0.2472]],

         [[-0.2382]]],


        [[[ 0.1271]],

         [[ 0.0681]],

         [[-0.2518]],

         [[ 0.2793]],

         [[-0.1661]],

         [[-0.2762]],

         [[-0.1974]],

         [[-0.0590]],

         [[-0.1549]],

         [[ 0.2146]],

         [[ 0.0872]],

         [[-0.2576]]],


        [[[ 0.0000]],

         [[-0.0000]],

         [[-0.0000]],

         [[ 0.0000]],

         [[-0.0000]],

         [[-0.0000]],

         [[ 0.0000]],

         [[ 0.0000]],

         [[ 0.0000]],

         [[-0.0000]],

         [[-0.0000]],

         [[-0.0000]]],


        [[[ 0.0000]],

         [[-0.0000]],

         [[-0.0000]],

         [[ 0.0000]],

         [[ 0.0000]],

         [[-0.0000]],

         [[-0.0000]],

     